import type { Metadata } from "next";
import { Geist, Geist_Mono

 } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import About from "@/components/about/About";
import Skills from "@/components/skills/Skills";
/*import Dev from "@/components/dev/Dev";*/
import Ln from "@/components/dev/ln";
/*import Blog from "@/components/blog/Blog";*/
import Projects from "@/components/project/Project";
import Certificates from "@/components/certificate/Certificate";
import Contact from "@/components/contact/Contact";
import Footer from "@/components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="min-h-full">
        <Navbar />
        {children}
        <About />
        <Skills />
        {/*<Dev />*/}
        <Ln />
        {/*<Blog/>*/}
        <Projects />
        <Certificates />
        <Contact />
        <Footer />
      </body>
    </html>
  );
}
